### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingException
  id: RemotingException
  children:
  - System.Runtime.Remoting.RemotingException.#ctor
  - System.Runtime.Remoting.RemotingException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingException
  nameWithType: RemotingException
  fullName: System.Runtime.Remoting.RemotingException
  type: Class
  summary: "Исключение, которое возникает, когда что-то пошло не так во время удаленного взаимодействия."
  remarks: "RemotingException использует COR_E_REMOTING HRESULT, который имеет значение 0x8013150B.       RemotingException использует значение по умолчанию <xref:System.Object.Equals%2A>реализацию, которая поддерживает равенство ссылок.</xref:System.Object.Equals%2A>       Список начальных значений свойств для экземпляра класса RemotingException см. в разделе RemotingException конструкторы."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException()
  nameWithType: RemotingException.RemotingException()
  fullName: System.Runtime.Remoting.RemotingException.RemotingException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> класса со свойствами по умолчанию."
  remarks: "<xref:System.Runtime.Remoting.RemotingException>наследует от <xref:System.SystemException>класса.</xref:System.SystemException></xref:System.Runtime.Remoting.RemotingException> В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingException>: | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Пустая строка (&quot;») |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(String)
  nameWithType: RemotingException.RemotingException(String)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> класса с использованием заданного сообщения."
  remarks: "<xref:System.Runtime.Remoting.RemotingException>наследует от <xref:System.SystemException>класса.</xref:System.SystemException></xref:System.Runtime.Remoting.RemotingException> В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingException>: | Тип свойства | Условие |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| `message` Строка |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(SerializationInfo,StreamingContext)
  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> класса из сериализованных данных."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке. (Дополнительные сведения о сериализации см. в разделе [сериализации XML и SOAP](~/add/includes/ajax-current-ext-md.md).)"
  syntax:
    content: protected RemotingException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Объект, содержащий сериализованные данные объекта."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Контекстные сведения об источнике или назначении исключения."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>info</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(String,Exception)
  nameWithType: RemotingException.RemotingException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения будет включать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или `null` Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingException>: | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Ссылка на внутреннее исключение. |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
    - id: InnerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `InnerException` не <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Runtime.Remoting.RemotingException.#ctor
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException()
  nameWithType: RemotingException.RemotingException()
  fullName: System.Runtime.Remoting.RemotingException.RemotingException()
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(String)
  nameWithType: RemotingException.RemotingException(String)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(SerializationInfo,StreamingContext)
  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(String,Exception)
  nameWithType: RemotingException.RemotingException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingException.#ctor*
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException
  nameWithType: RemotingException.RemotingException
