### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.DuplicateKeyException
  id: DuplicateKeyException
  children:
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  - System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  - System.Data.Linq.DuplicateKeyException.Object
  langs:
  - csharp
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException
  fullName: System.Data.Linq.DuplicateKeyException
  type: Class
  summary: "Возникает при попытке добавить объект в кэш идентификации с помощью ключа, который уже используется."
  syntax:
    content: 'public class DuplicateKeyException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  id: '#ctor(System.Object)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> класса."
  syntax:
    content: public DuplicateKeyException (object duplicate);
    parameters:
    - id: duplicate
      type: System.Object
      description: "Повторяющийся ключ, вызвавшую исключение, создаваемое исключение."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  id: '#ctor(System.Object,System.String)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> класса, ссылающиеся на повторяющийся ключ и сообщение об ошибке."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message);
    parameters:
    - id: duplicate
      type: System.Object
      description: "Повторяющийся ключ, вызвавшую исключение, создаваемое исключение."
    - id: message
      type: System.String
      description: "Сообщение, отображаемое при возникновении исключения."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  id: '#ctor(System.Object,System.String,System.Exception)'
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> класса, ссылающиеся на повторяющийся ключ, предоставив сообщение об ошибке и указав исключение, вызвавшее данное исключение, создаваемое исключение."
  syntax:
    content: public DuplicateKeyException (object duplicate, string message, Exception innerException);
    parameters:
    - id: duplicate
      type: System.Object
      description: "Повторяющийся ключ, вызвавшую исключение, создаваемое исключение."
    - id: message
      type: System.String
      description: "Сообщение, отображаемое при возникновении исключения."
    - id: innerException
      type: System.Exception
      description: "Предыдущее исключение, которое вызвало <xref href=&quot;System.Data.Linq.DuplicateKeyException&quot;> </xref> исключение."
  overload: System.Data.Linq.DuplicateKeyException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.DuplicateKeyException.Object
  id: Object
  parent: System.Data.Linq.DuplicateKeyException
  langs:
  - csharp
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
  type: Property
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Возвращает объект, вызвавший исключение."
  syntax:
    content: public object Object { get; }
    return:
      type: System.Object
      description: "Объект, который вызвал исключение."
  overload: System.Data.Linq.DuplicateKeyException.Object*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.DuplicateKeyException.#ctor(System.Object,System.String,System.Exception)
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException(Object,String,Exception)
  nameWithType: DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
  fullName: System.Data.Linq.DuplicateKeyException.DuplicateKeyException(Object,String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.DuplicateKeyException.Object
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
  fullName: System.Data.Linq.DuplicateKeyException.Object
- uid: System.Data.Linq.DuplicateKeyException.#ctor*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: DuplicateKeyException
  nameWithType: DuplicateKeyException.DuplicateKeyException
- uid: System.Data.Linq.DuplicateKeyException.Object*
  parent: System.Data.Linq.DuplicateKeyException
  isExternal: false
  name: Object
  nameWithType: DuplicateKeyException.Object
