### YamlMime:ManagedReference
items:
- uid: System.DuplicateWaitObjectException
  id: DuplicateWaitObjectException
  children:
  - System.DuplicateWaitObjectException.#ctor
  - System.DuplicateWaitObjectException.#ctor(System.String)
  - System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  - System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  langs:
  - csharp
  name: DuplicateWaitObjectException
  nameWithType: DuplicateWaitObjectException
  fullName: System.DuplicateWaitObjectException
  type: Class
  summary: "Исключение, возникающее, когда объект присутствует в массиве объектов синхронизации более одного раза."
  remarks: "Общеязыковая среда выполнения предоставляет механизм синхронизации потоков на основе объектов синхронизации, ожидающих выполнения в массиве <xref:System.Threading.WaitHandle>объектов.</xref:System.Threading.WaitHandle> Если массив <xref:System.Threading.WaitHandle>объекты передавать <xref:System.Threading.WaitHandle.WaitAll%2A>или <xref:System.Threading.WaitHandle.WaitAny%2A>все повторяющиеся операционной системой дескрипторов, создается исключение DuplicateWaitObjectException.</xref:System.Threading.WaitHandle.WaitAny%2A> </xref:System.Threading.WaitHandle.WaitAll%2A> </xref:System.Threading.WaitHandle> Дополнительные сведения см. в разделе <xref:System.Threading.WaitHandle>.</xref:System.Threading.WaitHandle>       DuplicateWaitObjectException использует COR_E_DUPLICATEWAITOBJECT HRESULT, который имеет значение 0x80131529.       Список начальных значений свойств для экземпляра класса DuplicateWaitObjectException см. в разделе <xref:System.DuplicateWaitObjectException.%23ctor%2A>конструкторов.</xref:System.DuplicateWaitObjectException.%23ctor%2A>      Настроек [!NOTE] настроек это исключение не включается в [.NET для магазина Windows](http://go.microsoft.com/fwlink/?LinkID=247912) или, но вызывается некоторые члены, которые являются. В этом случае перехватить исключение, запись `catch` инструкции для <xref:System.ArgumentException>вместо.</xref:System.ArgumentException>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class DuplicateWaitObjectException : ArgumentException
  inheritance:
  - System.ArgumentException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor
  id: '#ctor'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException()
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException()
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> класса."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>свойство нового экземпляра системным сообщением, которое описывает ошибку, например «Повторяющиеся объекты в аргументе».</xref:System.Exception.Message%2A> Это сообщение учитывает текущую культуру системы.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.ArgumentException.Message%2A>| Строка локализованного сообщения об. |</xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException ();
    parameters: []
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> класс с именем параметра, ставшего причиной этого исключения."
  remarks: "Содержимое `parameterName` предназначен должно быть понятно пользователю.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.ArgumentException.Message%2A>| Строка локализованного сообщения об. |   | <xref:System.ArgumentException.ParamName%2A>| Строка имени параметра. |</xref:System.ArgumentException.ParamName%2A> </xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string parameterName);
    parameters:
    - id: parameterName
      type: System.String
      description: "Имя параметра, вызвавшего исключение."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке. Дополнительные сведения см. в разделе [сериализации XML и SOAP](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected DuplicateWaitObjectException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Объект, содержащий сериализованные данные объекта."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Контекстные сведения об источнике или назначении."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String,Exception)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает значение, переданный этому конструктору.</xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Исключение, заданное параметром `innerException`. |   | <xref:System.ArgumentException.Message%2A>| Строка сообщения об ошибке определяется `message`. |</xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `innerException` не <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String,String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> класса с указанным сообщением об ошибке и именем параметра, ставшего причиной этого исключения."
  remarks: "Содержимое `parameterName` и `message` должно быть понятно пользователю. Код, вызывающий этот конструктор необходим для обеспечения локализации этих строк для текущего языка и региональных параметров системы.       Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или пустую ссылку (`Nothing` в Visual Basic) Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic) |   | <xref:System.ArgumentException.Message%2A>| Строка сообщения об ошибке. |   | <xref:System.ArgumentException.ParamName%2A>| Строка имени параметра. |</xref:System.ArgumentException.ParamName%2A> </xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string parameterName, string message);
    parameters:
    - id: parameterName
      type: System.String
      description: "Имя параметра, вызвавшего исключение."
    - id: message
      type: System.String
      description: "Сообщение, описывающее ошибку."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ArgumentException
  isExternal: false
  name: System.ArgumentException
- uid: System.DuplicateWaitObjectException.#ctor
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException()
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException()
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException()
- uid: System.DuplicateWaitObjectException.#ctor(System.String)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String,Exception)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String,String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
- uid: System.DuplicateWaitObjectException.#ctor*
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException
