### YamlMime:ManagedReference
items:
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  id: DispatcherUnhandledExceptionFilterEventArgs
  children:
  - System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception
  - System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  langs:
  - csharp
  name: DispatcherUnhandledExceptionFilterEventArgs
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs
  fullName: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  type: Class
  summary: "Предоставляет данные для <xref href=&quot;System.Windows.Threading.Dispatcher&quot;> </xref> <xref href=&quot;System.Windows.Threading.Dispatcher.UnhandledExceptionFilter&quot;> </xref> событий."
  remarks: "<xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>Событие происходит, когда код, выполняющийся посредством <xref:System.Windows.Threading.Dispatcher>создает исключение, которое не обрабатывается.</xref:System.Windows.Threading.Dispatcher> </xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>       <xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>Событий предоставляет средства для вызывает <xref:System.Windows.Threading.Dispatcher.UnhandledException>событий.</xref:System.Windows.Threading.Dispatcher.UnhandledException> </xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>  <xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>События во-первых и если <xref:System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch%2A>на DispatcherUnhandledExceptionFilterEventArgs задается `false`, <xref:System.Windows.Threading.Dispatcher.UnhandledException>события не вызываются.</xref:System.Windows.Threading.Dispatcher.UnhandledException> </xref:System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch%2A> </xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>"
  syntax:
    content: 'public sealed class DispatcherUnhandledExceptionFilterEventArgs : System.Windows.Threading.DispatcherEventArgs'
  inheritance:
  - System.EventArgs
  - System.Windows.Threading.DispatcherEventArgs
  implements: []
  inheritedMembers:
  - System.Windows.Threading.DispatcherEventArgs.Dispatcher
  platform:
  - net462
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception
  id: Exception
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.Exception
  fullName: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception
  type: Property
  assemblies:
  - WindowsBase
  namespace: System.Windows.Threading
  summary: "Возвращает исключение, возникшее при выполнении кода с помощью диспетчера."
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "Исключение."
  overload: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  id: RequestCatch
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  langs:
  - csharp
  name: RequestCatch
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  fullName: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  type: Property
  assemblies:
  - WindowsBase
  namespace: System.Windows.Threading
  summary: "Возвращает или задает должно быть порождено исключение и вызывать обработчики событий."
  remarks: "<xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>Событий предоставляет средства для вызывает <xref:System.Windows.Threading.Dispatcher.UnhandledException>событий.</xref:System.Windows.Threading.Dispatcher.UnhandledException> </xref:System.Windows.Threading.Dispatcher.UnhandledExceptionFilter>  <xref:System.Windows.Threading.Dispatcher.UnhandledException>— Вызванное первыми, а если RequestCatch на <xref:System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs>равно `false`, <xref:System.Windows.Threading.Dispatcher.UnhandledException>события не вызываются.</xref:System.Windows.Threading.Dispatcher.UnhandledException> </xref:System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs> </xref:System.Windows.Threading.Dispatcher.UnhandledException>       Предыдущий обработчик событий многоадресной рассылки может уже присвойте этому свойству значение `false`, указывающее, что исключение не перехватывается.  Поведение «не перехватывать» заменяет все остальные, поскольку скорее всего, значит сценариях отладки."
  syntax:
    content: public bool RequestCatch { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Если <xref href=&quot;System.Windows.Threading.Dispatcher.UnhandledException&quot;> </xref> должно быть вызываться, в противном случае; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>.  Значение по умолчанию — <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Threading.DispatcherEventArgs
  isExternal: false
  name: System.Windows.Threading.DispatcherEventArgs
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  isExternal: false
  name: Exception
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.Exception
  fullName: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  isExternal: false
  name: RequestCatch
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
  fullName: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.Exception*
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  isExternal: false
  name: Exception
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.Exception
- uid: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs.RequestCatch*
  parent: System.Windows.Threading.DispatcherUnhandledExceptionFilterEventArgs
  isExternal: false
  name: RequestCatch
  nameWithType: DispatcherUnhandledExceptionFilterEventArgs.RequestCatch
