### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingTimeoutException
  id: RemotingTimeoutException
  children:
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException
  fullName: System.Runtime.Remoting.RemotingTimeoutException
  type: Class
  summary: "Исключение, возникающее, когда сервера или клиента невозможен в течение ранее заданного времени."
  remarks: "RemotingTimeoutException возникает в том случае, если вызова удаленного взаимодействия не завершилась в отведенное время.       RemotingTimeoutException использует COR_E_REMOTING HRESULT, который имеет значение 0x8013150B.       RemotingTimeoutException использует значение по умолчанию <xref:System.Object.Equals%2A>реализацию, которая поддерживает равенство ссылок.</xref:System.Object.Equals%2A>       Список начальных значений свойств для экземпляра класса RemotingTimeoutException см. в разделе RemotingTimeoutException конструкторы."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.Remoting.RemotingException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> класса со свойствами по умолчанию."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>наследует от <xref:System.Exception>класса.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Локализованное сообщение об ошибке для <xref:System.Runtime.Remoting.RemotingTimeoutException>|</xref:System.Runtime.Remoting.RemotingTimeoutException> </xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> класса с использованием заданного сообщения."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException>наследует от <xref:System.Exception>класса.</xref:System.Exception></xref:System.Runtime.Remoting.RemotingTimeoutException> В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Тип свойства | Условие |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| `message` Строка |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, указывающее причину возникновения исключения."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения необходимо включить ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или `null` Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Runtime.Remoting.RemotingTimeoutException>: | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Ссылка на внутреннее исключение |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
    - id: InnerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `InnerException` не <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: System.Runtime.Remoting.RemotingException
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException.RemotingTimeoutException
