### YamlMime:ManagedReference
items:
- uid: System.Web.HttpUnhandledException
  id: HttpUnhandledException
  children:
  - System.Web.HttpUnhandledException.#ctor
  - System.Web.HttpUnhandledException.#ctor(System.String)
  - System.Web.HttpUnhandledException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: HttpUnhandledException
  nameWithType: HttpUnhandledException
  fullName: System.Web.HttpUnhandledException
  type: Class
  summary: "Исключение, которое выдается при возникновении универсального исключения."
  syntax:
    content: 'public sealed class HttpUnhandledException : System.Web.HttpException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.InteropServices.ExternalException
  - System.Web.HttpException
  implements: []
  inheritedMembers:
  - System.Runtime.InteropServices.ExternalException.ErrorCode
  - System.Runtime.InteropServices.ExternalException.ToString
  - System.Web.HttpException.CreateFromLastError(System.String)
  - System.Web.HttpException.GetHtmlErrorMessage
  - System.Web.HttpException.GetHttpCode
  - System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Web.HttpException.WebEventCode
  platform:
  - net462
- uid: System.Web.HttpUnhandledException.#ctor
  id: '#ctor'
  parent: System.Web.HttpUnhandledException
  langs:
  - csharp
  name: HttpUnhandledException()
  nameWithType: HttpUnhandledException.HttpUnhandledException()
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Web.HttpUnhandledException&quot;> </xref> класса."
  syntax:
    content: public HttpUnhandledException ();
    parameters: []
  overload: System.Web.HttpUnhandledException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.HttpUnhandledException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.HttpUnhandledException
  langs:
  - csharp
  name: HttpUnhandledException(String)
  nameWithType: HttpUnhandledException.HttpUnhandledException(String)
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Web.HttpUnhandledException&quot;> </xref> класса указанные сообщения об ошибках."
  syntax:
    content: public HttpUnhandledException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, отображаемое для клиента при возникновении исключения."
  overload: System.Web.HttpUnhandledException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.HttpUnhandledException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Web.HttpUnhandledException
  langs:
  - csharp
  name: HttpUnhandledException(String,Exception)
  nameWithType: HttpUnhandledException.HttpUnhandledException(String,Exception)
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException(String,Exception)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Web.HttpUnhandledException&quot;> </xref> класса с указанной ошибкой сообщением и внутренним исключением."
  syntax:
    content: public HttpUnhandledException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, отображаемое для клиента при возникновении исключения."
    - id: innerException
      type: System.Exception
      description: "<xref:System.Exception.InnerException*>, Если таковое имеется, которое вызвало текущее исключение.</xref:System.Exception.InnerException*>"
  overload: System.Web.HttpUnhandledException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.HttpException
  isExternal: false
  name: System.Web.HttpException
- uid: System.Web.HttpUnhandledException.#ctor
  parent: System.Web.HttpUnhandledException
  isExternal: false
  name: HttpUnhandledException()
  nameWithType: HttpUnhandledException.HttpUnhandledException()
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException()
- uid: System.Web.HttpUnhandledException.#ctor(System.String)
  parent: System.Web.HttpUnhandledException
  isExternal: false
  name: HttpUnhandledException(String)
  nameWithType: HttpUnhandledException.HttpUnhandledException(String)
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.HttpUnhandledException.#ctor(System.String,System.Exception)
  parent: System.Web.HttpUnhandledException
  isExternal: false
  name: HttpUnhandledException(String,Exception)
  nameWithType: HttpUnhandledException.HttpUnhandledException(String,Exception)
  fullName: System.Web.HttpUnhandledException.HttpUnhandledException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Web.HttpUnhandledException.#ctor*
  parent: System.Web.HttpUnhandledException
  isExternal: false
  name: HttpUnhandledException
  nameWithType: HttpUnhandledException.HttpUnhandledException
